### ISSUE TITLE
Can Timelapse Move Randomly Selected Files to a New Folder?

### ISSUE THREAD

**Issue by marireeves** [saulgreenberg/Timelapse#1]
Hi Saul - Thank you so much for this amazing software! We are using it on several projects and it's awesome!

So, when you delete files, it simply moves them into a folder called "DeletedFiles". I'm developing a test set for training an AI agent, and wanted to use the timelapse function to randomly select images that meet certain criteria. I did this, and got a CSV file, but now am writing a script to find those files and move them to a separate folder "TrainingData". I don't want to re-invent the wheel, so thought I'd check if Timelapse can do this already and I haven't found the button. 

Please let me know, thanks!

**Comment by saulgreenberg** [comment]
Absolutely –

  1.  Use Select to select the subset of files you want
  2.  Then Menu: File| Export (copy) all images and video files in the current selection
  3.  You will then see this dialog below, which allows you to export those files to a particular location
  4.  Tada!
Saul
***@***.***
From: Mari K Reeves ***@***.***>
Sent: September 6, 2022 5:26 PM
To: saulgreenberg/Timelapse ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [saulgreenberg/Timelapse] Can Timelapse Move Randomly Selected Files to a New Folder? (Issue #1)

[△EXTERNAL]


Hi Saul - Thank you so much for this amazing software! We are using it on several projects and it's awesome!

So, when you delete files, it simply moves them into a folder called "DeletedFiles". I'm developing a test set for training an AI agent, and wanted to use the timelapse function to randomly select images that meet certain criteria. I did this, and got a CSV file, but now am writing a script to find those files and move them to a separate folder "TrainingData". I don't want to re-invent the wheel, so thought I'd check if Timelapse can do this already and I haven't found the button.

Please let me know, thanks!

**Comment by saulgreenberg** [comment]
PS Its best to contact me directly rather than through Github: ***@***.******@***.***>
Saul

From: Mari K Reeves ***@***.***>
Sent: September 6, 2022 5:26 PM
To: saulgreenberg/Timelapse ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [saulgreenberg/Timelapse] Can Timelapse Move Randomly Selected Files to a New Folder? (Issue #1)

[△EXTERNAL]


Hi Saul - Thank you so much for this amazing software! We are using it on several projects and it's awesome!

So, when you delete files, it simply moves them into a folder called "DeletedFiles". I'm developing a test set for training an AI agent, and wanted to use the timelapse function to randomly select images that meet certain criteria. I did this, and got a CSV file, but now am writing a script to find those files and move them to a separate folder "TrainingData". I don't want to re-invent the wheel, so thought I'd check if Timelapse can do this already and I haven't found the button.

Please let me know, thanks!
