### ISSUE TITLE
export coordinates of markers

### ISSUE THREAD

**Issue by petrasovaa** [saulgreenberg/Timelapse#33]
When counting using markers, is it possible to save and export the position of the marker in the coordinate system of the image? If not would it be difficult to add this feature in there?

Thank you

**Comment by saulgreenberg** [comment]
The positions are currently saved as a ratio of width and height eg if it's right in the middle, it would be .5 and .5. This means you can always calculate the position even if the image is scaled. They are currently stored in the database... while I could put in a feature to export it in the spreadsheet, it's more complicated as you would think as each marker is associated with a particular counter field. So it would have the done as two tables that would need to be cross referenced.

If you let me know why you need it (and perhaps in what form) then I can see if there is a reasonable solution.

Ps the last section of the user manual shows how the coordinates are stored in the database.  Since it's a standard sql database, if you know how to read those then you can access that information from there rather than from the spreadsheet

Saul Greenberg
Sent from my iPhone with the usual bizarre spelling corrections

On Jul 27, 2017, at 1:28 PM, Anna Petrasova <notifications@github.com<mailto:notifications@github.com>> wrote:


When counting using markers, is it possible to save and export the position of the marker in the coordinate system of the image? If not would it be difficult to add this feature in there?

Thank you

**Comment by saulgreenberg** [comment]
Ps. The complete timelapse package, including manuals, Mailing list info, and other installation /documentation info is at http://saul.cpsc.ucalgary.ca/timelapse

The github repository is normally for developers - the main web sight is more suitable for end users.

Saul Greenberg
Sent from my iPhone with the usual bizarre spelling corrections

On Jul 27, 2017, at 1:35 PM, Saul Greenberg <saul@ucalgary.ca<mailto:saul@ucalgary.ca>> wrote:

The positions are currently saved as a ratio of width and height eg if it's right in the middle, it would be .5 and .5. This means you can always calculate the position even if the image is scaled. They are currently stored in the database... while I could put in a feature to export it in the spreadsheet, it's more complicated as you would think as each marker is associated with a particular counter field. So it would have the done as two tables that would need to be cross referenced.

If you let me know why you need it (and perhaps in what form) then I can see if there is a reasonable solution.

Ps the last section of the user manual shows how the coordinates are stored in the database.  Since it's a standard sql database, if you know how to read those then you can access that information from there rather than from the spreadsheet

Saul Greenberg
Sent from my iPhone with the usual bizarre spelling corrections

On Jul 27, 2017, at 1:28 PM, Anna Petrasova <notifications@github.com<mailto:notifications@github.com>> wrote:


When counting using markers, is it possible to save and export the position of the marker in the coordinate system of the image? If not would it be difficult to add this feature in there?

Thank you

**Comment by petrasovaa** [comment]
Sorry, I should have seen it there. This is enough for me now. Thank you!
